from __future__ import annotations

from pathlib import Path

from ai_ime.models import LearnedRule

AI_IME_LUA_MODULE = "ai_ime_logger"
AI_IME_LUA_PROCESSOR = "*ai_ime_logger"
AI_IME_LUA_BOOTSTRAP_START = "-- AI IME logger bootstrap: start"
AI_IME_LUA_BOOTSTRAP_END = "-- AI IME logger bootstrap: end"

DICT_HEADER_TEMPLATE = """# Rime dictionary
# encoding: utf-8
# Generated by AI IME. Review before copying into your Rime user data directory.
---
name: {dictionary_id}
version: "{version}"
sort: by_weight
use_preset_vocabulary: true
{import_tables}
...
"""


def render_dictionary(
    rules: list[LearnedRule],
    dictionary_id: str = "ai_typo",
    base_dictionary: str = "",
    version: str = "0.1.0",
) -> str:
    lines = [
        DICT_HEADER_TEMPLATE.format(
            dictionary_id=dictionary_id,
            import_tables=_render_import_tables(base_dictionary),
            version=version,
        ).rstrip(),
        "",
    ]
    for text, pinyin, weight in _dedupe_entries(rules):
        lines.append(f"{text}\t{pinyin}\t{weight}")
    return "\n".join(lines).rstrip() + "\n"


def render_schema_patch(dictionary_id: str = "ai_typo") -> str:
    lua_processor = render_lua_processor_patch()
    translator = render_typo_translator_patch(dictionary_id=dictionary_id)
    return (
        "# Rime schema patch\n"
        "# Generated by AI IME. Merge carefully if this file already exists.\n"
        "patch:\n"
        f"{lua_processor}"
        f"{translator}"
    )


def render_lua_processor_patch(processor_name: str = AI_IME_LUA_PROCESSOR) -> str:
    return f"  engine/processors/@before 0: lua_processor@{processor_name}\n"


def render_typo_translator_patch(dictionary_id: str = "ai_typo") -> str:
    return (
        f"  engine/translators/@before 1: table_translator@{dictionary_id}\n"
        f"  {dictionary_id}:\n"
        f"    dictionary: {dictionary_id}\n"
        "    enable_sentence: false\n"
        "    enable_user_dict: false\n"
        "    initial_quality: 50\n"
    )


def render_lua_bootstrap(
    module_name: str = AI_IME_LUA_MODULE,
    processor_name: str = "ai_ime_logger_processor",
) -> str:
    return (
        f"{AI_IME_LUA_BOOTSTRAP_START}\n"
        f"local ai_ime_logger = require(\"{module_name}\")\n"
        f"{processor_name} = ai_ime_logger.processor\n"
        f"{AI_IME_LUA_BOOTSTRAP_END}\n"
    )


def merge_lua_bootstrap(content: str) -> str:
    lines = _remove_generated_lua_bootstrap_lines(content.splitlines())
    prefix = "\n".join(lines).rstrip()
    bootstrap = render_lua_bootstrap().rstrip()
    if prefix:
        return f"{prefix}\n\n{bootstrap}\n"
    return f"{bootstrap}\n"


def remove_lua_bootstrap(content: str) -> str:
    return "\n".join(_remove_generated_lua_bootstrap_lines(content.splitlines())).rstrip() + "\n"


def render_lua_logger(log_path: Path, enabled: bool = True) -> str:
    return f"""-- Generated by AI IME. This module records Rime commit events for typo learning.
local M = {{}}

local LOG_PATH = {_lua_long_string(str(log_path))}
local LOCK_PATH = LOG_PATH .. ".lock"
local ENABLED = {_lua_bool(enabled)}
local kNoop = 2

local function safe_call(fn, default)
  local ok, result = pcall(fn)
  if ok and result ~= nil then
    return result
  end
  return default
end

local function json_escape(value)
  if value == nil then
    return ""
  end
  value = tostring(value)
  value = value:gsub("\\\\", "\\\\\\\\")
  value = value:gsub('"', '\\\\"')
  value = value:gsub("\\r", "\\\\r")
  value = value:gsub("\\n", "\\\\n")
  value = value:gsub("\\t", "\\\\t")
  return value
end

local function json_string(value)
  return '"' .. json_escape(value) .. '"'
end

local function json_number_or_null(value)
  if type(value) == "number" then
    return tostring(value)
  end
  return "null"
end

local function acquire_lock()
  for _ = 1, 120 do
    local token = LOCK_PATH .. ".rime." .. tostring(os.time()) .. "." .. tostring(math.random(1000000))
    local marker = io.open(token, "w")
    if marker ~= nil then
      marker:write("rime-lua")
      marker:close()
      if os.rename(token, LOCK_PATH) then
        return true
      end
      os.remove(token)
    end
  end
  return false
end

local function release_lock()
  os.remove(LOCK_PATH)
end

local function append_event(event)
  if not ENABLED then
    return
  end
  if not acquire_lock() then
    return
  end
  local file = io.open(LOG_PATH, "a")
  if not file then
    release_lock()
    return
  end
  file:write("{{")
  file:write('"timestamp":' .. json_number_or_null(os.time()))
  file:write(',"event_type":' .. json_string(event.event_type))
  file:write(',"name":' .. json_string(event.name))
  file:write(',"pinyin":' .. json_string(event.pinyin))
  file:write(',"committed_text":' .. json_string(event.committed_text))
  file:write(',"role":' .. json_string(event.role))
  file:write(',"source":' .. json_string("rime-lua"))
  file:write(',"candidate_text":' .. json_string(event.candidate_text))
  file:write(',"candidate_comment":' .. json_string(event.candidate_comment))
  file:write(',"selection_index":' .. json_number_or_null(event.selection_index))
  file:write(',"commit_key":' .. json_string(event.commit_key))
  file:write("}}\\n")
  file:close()
  release_lock()
end

local function key_code(key)
  return safe_call(function() return key.keycode end, nil)
end

local function key_name(key)
  local code = key_code(key)
  if code == 0x20 then
    return "space"
  elseif code == 0xff0d or code == 0xff8d then
    return "enter"
  elseif code == 0xff08 then
    return "backspace"
  elseif code == 0xffff then
    return "delete"
  elseif code ~= nil and code >= 0x30 and code <= 0x39 then
    return string.char(code)
  elseif code ~= nil and code >= 0xffb0 and code <= 0xffb9 then
    return tostring(code - 0xffb0)
  end
  return safe_call(function() return key:repr() end, "")
end

local function selection_index_from_key(key, env)
  local name = key_name(key)
  if name == "space" or name == "enter" then
    return safe_call(function() return env.engine.context:get_selected_candidate_index() end, 0) or 0
  end
  local select_keys = safe_call(function() return env.engine.schema.select_keys end, "")
  if select_keys ~= nil and select_keys ~= "" and #name == 1 then
    local pos = string.find(select_keys, name, 1, true)
    if pos ~= nil then
      return pos - 1
    end
  end
  if #name == 1 and name >= "1" and name <= "9" then
    return tonumber(name) - 1
  elseif name == "0" then
    return 9
  end
  return nil
end

local function candidate_at(context, index)
  local candidate = nil
  if index ~= nil then
    candidate = safe_call(function()
      local composition = context.composition
      if composition == nil or composition:empty() then
        return nil
      end
      local segment = composition:back()
      if segment == nil then
        return nil
      end
      return segment:get_candidate_at(index)
    end, nil)
  end
  if candidate == nil then
    candidate = safe_call(function() return context:get_selected_candidate() end, nil)
  end
  return candidate
end

local function capture_context(context, key, env)
  local index = nil
  local commit_key = ""
  if key ~= nil then
    index = selection_index_from_key(key, env)
    commit_key = key_name(key)
  end
  local input = safe_call(function() return context.input end, "") or ""
  local candidate = candidate_at(context, index)
  local candidate_text = ""
  local candidate_comment = ""
  if candidate ~= nil then
    candidate_text = safe_call(function() return candidate.text end, "") or ""
    candidate_comment = safe_call(function() return candidate.comment end, "") or ""
  end
  return {{
    input = input,
    candidate_text = candidate_text,
    candidate_comment = candidate_comment,
    selection_index = index,
    commit_key = commit_key,
  }}
end

local function is_confirm_key(key, env)
  return selection_index_from_key(key, env) ~= nil
end

local function is_delete_key(key)
  local name = key_name(key)
  return name == "backspace" or name == "delete"
end

function M.init(env)
  math.randomseed(os.time())
  env.ai_ime_pending_commit = nil
  env.ai_ime_commit_connection = env.engine.context.commit_notifier:connect(function(context)
    local pending = env.ai_ime_pending_commit or capture_context(context, nil, env)
    local commit_text = safe_call(function() return context:get_commit_text() end, "") or ""
    if commit_text == "" then
      commit_text = pending.candidate_text or ""
    end
    local input = pending.input or safe_call(function() return context.input end, "") or ""
    append_event({{
      event_type = "commit",
      name = input,
      pinyin = input,
      committed_text = commit_text,
      role = "rime_commit",
      candidate_text = pending.candidate_text or commit_text,
      candidate_comment = pending.candidate_comment or "",
      selection_index = pending.selection_index,
      commit_key = pending.commit_key or "",
    }})
    env.ai_ime_pending_commit = nil
  end)
end

function M.fini(env)
  env.ai_ime_pending_commit = nil
end

function M.func(key, env)
  if not ENABLED then
    return kNoop
  end
  if safe_call(function() return key:release() end, false) then
    return kNoop
  end
  local context = env.engine.context
  if is_delete_key(key) then
    append_event({{
      event_type = "down",
      name = key_name(key),
      pinyin = "",
      committed_text = "",
      role = "rime_edit",
      candidate_text = "",
      candidate_comment = "",
      selection_index = nil,
      commit_key = key_name(key),
    }})
    return kNoop
  end
  if safe_call(function() return context:is_composing() end, false) and is_confirm_key(key, env) then
    env.ai_ime_pending_commit = capture_context(context, key, env)
  end
  return kNoop
end

M.processor = {{
  init = M.init,
  fini = M.fini,
  func = M.func,
}}

return M
"""


def export_rime_files(
    rules: list[LearnedRule],
    output_dir: Path,
    schema_id: str = "luna_pinyin",
    dictionary_id: str = "ai_typo",
    base_dictionary: str = "",
) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    dictionary_path = output_dir / f"{dictionary_id}.dict.yaml"
    patch_path = output_dir / f"{schema_id}.custom.yaml"
    dictionary_path.write_text(
        render_dictionary(rules, dictionary_id=dictionary_id, base_dictionary=base_dictionary),
        encoding="utf-8",
        newline="\n",
    )
    patch_path.write_text(render_schema_patch(dictionary_id=dictionary_id), encoding="utf-8", newline="\n")
    return dictionary_path, patch_path


def _dedupe_entries(rules: list[LearnedRule]) -> list[tuple[str, str, int]]:
    entries: dict[tuple[str, str], int] = {}
    for rule in rules:
        if not rule.enabled:
            continue
        key = (rule.committed_text, rule.wrong_pinyin)
        entries[key] = max(entries.get(key, 0), rule.weight)
    return [
        (text, pinyin, weight)
        for (text, pinyin), weight in sorted(entries.items(), key=lambda item: (-item[1], item[0][1], item[0][0]))
    ]


def _render_import_tables(base_dictionary: str) -> str:
    if not base_dictionary.strip():
        return ""
    return f"import_tables:\n  - {base_dictionary.strip()}"


def _remove_generated_lua_bootstrap_lines(lines: list[str]) -> list[str]:
    output: list[str] = []
    skipping = False
    for line in lines:
        if line.strip() == AI_IME_LUA_BOOTSTRAP_START:
            skipping = True
            continue
        if line.strip() == AI_IME_LUA_BOOTSTRAP_END:
            skipping = False
            continue
        if not skipping:
            output.append(line)
    return output


def _lua_bool(value: bool) -> str:
    return "true" if value else "false"


def _lua_long_string(value: str) -> str:
    marker = ""
    while f"]{marker}]" in value:
        marker += "="
    return f"[{marker}[{value}]{marker}]"
