from __future__ import annotations

from pathlib import Path

from ai_ime.models import LearnedRule


DICT_HEADER_TEMPLATE = """# Rime dictionary
# encoding: utf-8
# Generated by AI IME. Review before copying into your Rime user data directory.
---
name: {dictionary_id}
version: "{version}"
sort: by_weight
use_preset_vocabulary: true
import_tables:
  - {base_dictionary}
...
"""


def render_dictionary(
    rules: list[LearnedRule],
    dictionary_id: str = "ai_typo",
    base_dictionary: str = "luna_pinyin",
    version: str = "0.1.0",
) -> str:
    lines = [
        DICT_HEADER_TEMPLATE.format(
            dictionary_id=dictionary_id,
            base_dictionary=base_dictionary,
            version=version,
        ).rstrip(),
        "",
    ]
    for text, pinyin, weight in _dedupe_entries(rules):
        lines.append(f"{text}\t{pinyin}\t{weight}")
    return "\n".join(lines).rstrip() + "\n"


def render_schema_patch(dictionary_id: str = "ai_typo") -> str:
    translator = render_typo_translator_patch(dictionary_id=dictionary_id)
    return (
        "# Rime schema patch\n"
        "# Generated by AI IME. Merge carefully if this file already exists.\n"
        "patch:\n"
        f"{translator}"
    )


def render_typo_translator_patch(dictionary_id: str = "ai_typo") -> str:
    return (
        f"  engine/translators/@before 1: table_translator@{dictionary_id}\n"
        f"  {dictionary_id}:\n"
        f"    dictionary: {dictionary_id}\n"
        "    enable_sentence: false\n"
        "    enable_user_dict: false\n"
        "    initial_quality: 50\n"
    )


def export_rime_files(
    rules: list[LearnedRule],
    output_dir: Path,
    schema_id: str = "luna_pinyin",
    dictionary_id: str = "ai_typo",
    base_dictionary: str = "luna_pinyin",
) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    dictionary_path = output_dir / f"{dictionary_id}.dict.yaml"
    patch_path = output_dir / f"{schema_id}.custom.yaml"
    dictionary_path.write_text(
        render_dictionary(rules, dictionary_id=dictionary_id, base_dictionary=base_dictionary),
        encoding="utf-8",
        newline="\n",
    )
    patch_path.write_text(render_schema_patch(dictionary_id=dictionary_id), encoding="utf-8", newline="\n")
    return dictionary_path, patch_path


def _dedupe_entries(rules: list[LearnedRule]) -> list[tuple[str, str, int]]:
    entries: dict[tuple[str, str], int] = {}
    for rule in rules:
        if not rule.enabled:
            continue
        key = (rule.committed_text, rule.wrong_pinyin)
        entries[key] = max(entries.get(key, 0), rule.weight)
    return [
        (text, pinyin, weight)
        for (text, pinyin), weight in sorted(entries.items(), key=lambda item: (-item[1], item[0][1], item[0][0]))
    ]
